# v0.10.2 middle-section review

Reviewed on 2026-09-28. Scope: Part II divider, Chapters 6 through 9, Part III divider, and Chapters 10 through 14. These eleven canonical sections contained 36,746 whitespace-delimited words before this pass. Every paragraph, narrative scene, caption, equation, table, and closing precedent was read. The edited sections contain 37,058 words by the same measure. This is an editorial coverage count, not the publication's word-count authority.

The review followed `CLAUDE.md`, the canonical-content section of `README.md`, `VOICE-GUIDE.md`, `ELIJAH-PROTOCOL.md`, and the applicable machine instructions. The argument, narrative, and field-manual registers remain distinct. The author's food-first proposal, 2027 forecast, ownership position, cast, and overall chronology remain intact. Injected chapter-header illustrations and epigraphs were preserved.

`middle-changes.json` records all 45 exact replacements with a rationale. Nine chapters changed; both dividers were reviewed and retained. No publication output, shared metadata, image file, registry, Appendix B, or build script was edited by this reviewer.

## Coverage and decisions

| Section | Review result |
| --- | --- |
| Part II divider | Retained. Its nineteen-household example is explicitly a beginning, and the cast image caption identifies the four pictured people without claiming they are the complete cast. |
| Chapter 6 | Narrowed a three-sector price-versus-wage claim to housing, the subject of the evidence actually supplied. Checked the 2024 food-insecurity figures against ERS and retained their household-versus-individual distinction. Preserved the Claypot departure, first meeting, broom, and check-engine-light setup. |
| Chapter 7 | Removed one narrative moral already expressed by the names in Elijah's notebook. Replaced an unsupported payroll superlative. Credited the full scarcity-study team, added the paper beside the finding, and stopped treating a harvest comparison as proof that food provision guarantees cognitive recovery. Kept the cooperative argument while accounting for a shock that hits the whole region. Qualified the claim that all trust must be local and the claim that no organized opposition to printing ever existed. Used the regulator's school-bus letter rather than secondary coverage. Clarified that the AFM campaign failed to preserve orchestra jobs while its bargaining produced a durable institution. |
| Chapter 8 | Preserved the Gary/Sal revision, the unearned meal, the attention-study boundaries, and the repeated-game analogy. Made the proposed 24-hour delay apply to commentary, with urgent information still actionable. Replaced a misleading contrast between a protocol and a contract with an instruction to write down the arrangement. |
| Chapter 9 | Kept the controller commissioning, repairability, human support, five-household example, and quantified shortfall. Matched ammonia's energy denominator and emissions boundary to the IEA assessment. Checked the Mycodo installation command against its official repository without executing it. Clarified that a PID expression does not itself set valve run-time, water-use, or failed-sensor limits. |
| Part III divider | Retained. The forecast is explicitly the author's bet; participation does not require land or hardware ownership. |
| Chapter 10 | Matched Denny's assembly action to the printed PETG cases in Chapter 9. Had the terminal correction reach the actual growers, not only the video audience. Removed a repeated food-picture metaphor. Preserved the model-collapse example but stated its experimental boundary. Replaced an absolute claim of offline invisibility with the actual recording boundary. Qualified and sourced US barter-tax treatment. |
| Chapter 11 | Kept the 41-hour incident, the engineering failure, the consent to publication, and the hardware estimates with their existing caveats. Put notice review with counsel instead of implying a paralegal decides the legal duty or that county boundaries determine it. Corrected the lockout analogy to servicing, all energy sources, stored energy, and verification. Clarified what an air gap isolates. Removed the repeated radiator sound and never-billing line from the closing paragraph. |
| Chapter 12 | Preserved uncertainty about buyers sharing a registered agent. Replaced an absolute claim that owning land guarantees a building site with concrete pre-purchase checks. Sourced and qualified the 99-year ground lease. Replaced a sum of unlike resources with separate weekly resource accounts, prior commitments, and reserves; requests still need suitable supply and delivery. Corrected the network image's claim of automated deliveries. Corrected the Homestead Act timeline while preserving the paid early-title exception. |
| Chapter 13 | Distinguished interior double-wall connector pipe from the listed insulated chimney through the roof. Kept socks on a drying rack clear of the stove. Changed the temporary-housing suggestion from an occupied RV inside a utility building to an approved outdoor arrangement. Corrected Fourier notation to heat-transfer rate and stated its uniform-layer assumption. Replaced a tax-credit reference with DOE's construction guide for insulation. Preserved the broken weld, Marta's authority, qualified electrician, first fire, and call to Elijah's mother. |
| Chapter 14 | Removed the claim that just-in-time entails no stock or slack and cited Toyota's own account. Marked the logistics sequence as hypothetical, with no empirical four-day countdown. Dated the USDA food-loss baseline and California's 2025 target, and distinguished a target from achievement. Clarified that unlike loss and food-insecurity quantities do not compute meals available. Repaired the Kodak/Fujifilm mechanism so it no longer contradicts the preceding account of Kodak's digital investment. Preserved Frank's agency, negotiated job, records, bell, and Devendra callback. |

## Sources checked and evidence boundaries

The following primary or institutional sources were opened or searched for the specific issues under review. Their presence is not a claim that every historical sentence or epigraph in these chapters was independently re-established from an original archive during this pass.

- [Mani, Mullainathan, Shafir, and Zhao, Poverty Impedes Cognitive Function](https://doi.org/10.1126/science.1238041), with [the authors' deposited paper](https://shafir.scholar.princeton.edu/document/9). Supports the reported test comparison. It does not evaluate the book's food service or prove the effect for every person.
- [NHTSA, November 24, 2025 letter to Waymo](https://static.nhtsa.gov/odi/inv/2025/INOT-PE25013-30887.pdf). Establishes the school-bus inquiry and the regulator's request; it is not a completed finding about every reported event.
- [IEA, Ammonia Technology Roadmap, executive summary](https://www.iea.org/reports/ammonia-technology-roadmap/executive-summary). The revised prose uses its 2021 assessment, global final-energy boundary including feedstock, and direct annual CO₂ figure. It does not treat production emissions as the complete fertilizer life cycle.
- [Mycodo official repository](https://github.com/kizniche/Mycodo#install-mycodo). The existing installer URL and HTTPS interface address match the documentation. The current README identifies tested operating systems; the book already tells readers to check requirements. No installer ran and no live controller was commissioned during review.
- [Shumailov and colleagues, Nature, 2024](https://www.nature.com/articles/s41586-024-07566-y). The model-collapse discussion remains a description of recursive training under studied conditions. The transition-kernel equation remains labeled schematic, and the image remains illustrative.
- [IRS, What is taxable and nontaxable income?](https://www.irs.gov/businesses/small-businesses-self-employed/what-is-taxable-and-nontaxable-income). Supports the US barter-income statement and the distinction for some informal noncommercial exchanges of similar services. The prose gives no personalized tax conclusion.
- [NIST glossary, air gap](https://csrc.nist.gov/glossary/term/air_gap), referencing the definition in [RFC 4949](https://www.rfc-editor.org/rfc/rfc4949.html). Physical isolation and manual transfer do not prove a model's outputs or imported files safe.
- [California Attorney General, Data Security Breach Reporting](https://oag.ca.gov/privacy/databreach/reporting). Notification duties depend on defined information and statutory conditions. The fictional facts are not sufficient to pronounce a legal outcome, so counsel reviews them in the story.
- [OSHA, 29 CFR 1910.147](https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.147). Supports the corrected servicing and hazardous-energy language, including stored energy and verification. The scene is still an analogy, not a complete energy-control procedure.
- [Grounded Solutions Network, Community Land Trusts](https://groundedsolutions.org/strengthening-neighborhoods/community-land-trusts/). Describes often 99-year renewable leases. The prose now leaves individual rights and obligations to the actual agreement.
- [Homestead Act transcript, National Archives](https://www.archives.gov/milestone-documents/homestead-act) and [Daniel Freeman's January 20, 1868 certificate, US Capitol Visitor Center](https://www.visitthecapitol.gov/artifact/homesteading-certificate-eligibility-daniel-freeman-january-20-1868). Ordinary five-year proof after an 1863 filing cannot be completed by the war's 1865 end. The Act also permitted paid early acquisition, which the correction retains.
- [USDA NASS, Land Values 2026](https://www.nass.usda.gov/Publications/Todays_Reports/reports/land0726.pdf). Verified $4,500 average farm real estate, $6,020 cropland, $2,000 pasture, and the 3.4 percent annual farm-real-estate change. The national nominal averages remain explicitly distinct from local offers and inflation-adjusted values.
- [USDA ERS, Household Food Security in the United States in 2024](https://www.ers.usda.gov/media/9161/err-358.pdf?v=35619). Verified 47.9 million people living in food-insecure households, the 7.3 million child category, and Table 2's 39.4 and 7.9 percent selected household-income groups. Existing captions already avoid claiming causation.
- [Duravent, DVL product documentation](https://duravent.com/product/dvl) and [typical installation components](https://duravent.com/literature/L923_W.pdf). Distinguishes interior stovepipe from the manufactured chimney. It does not approve a salvaged stove, a particular site, or every local installation.
- [US Fire Administration, Heating Fire Safety](https://www.usfa.fema.gov/prevention/home-fires/prevent-fires/heating/) and [CDC, Carbon Monoxide Poisoning Basics](https://www.cdc.gov/carbon-monoxide/about/index.html). Support keeping combustible objects clear and not assuming enclosed fuel-burning equipment is safe. The proposed temporary living arrangement still requires actual local approval.
- [DOE, Energy Renovations: Insulation](https://www.energy.gov/sites/default/files/2023-03/insulation_guide_0.pdf). Addresses trained foam installation, manufacturer requirements, and fire protection. It is not a container-home structural or moisture design.
- [Toyota, Production System](https://global.toyota/en/company/vision-and-philosophy/production-system/). Its own description explicitly includes minimum parts stocks. It does not establish a grocery store's reserve duration.
- [USDA, Food Waste FAQs](https://www.usda.gov/about-food/food-safety/food-loss-and-waste/food-waste-faqs). Its 30 to 40 percent summary points to a 2010 retail/consumer estimate. It is not a 2026 measurement or a count of safe donation-ready meals.
- [CalRecycle, Food Recovery](https://calrecycle.ca.gov/organics/slcp/foodrecovery/). The 20 percent recovery target was for 2025. The revised text does not report attainment.
- [Kodak, Milestones](https://www.kodak.com/en/company/page/milestones/). Kodak's substantial digital participation remains explicit. Corporate history is evidence of actions, not proof that only one strategic cause explains the companies' different outcomes.

## Shared corrections handed off

These are requests to the parent/relevant owner, not files changed by this reviewer:

1. `ELIJAH-PROTOCOL.md`: Denny's two dated layoffs are 2019 and 2023, which span four years. The older cast summary says three. Preserve the chapter dates and update the guide.
2. `ch14-logistic-shockwave.svg`: remove or unmistakably label the invented day-by-day timetable. The chapter's alt text and caption are already corrected.
3. `ch12-csa-network.svg`: match the human delivery, limited scheduling assistance, and resource-specific surplus account. The chapter's alt text and caption are already corrected.
4. Glossary's network-surplus definition: coordinated directly with the ending reviewer so it matches Chapter 12's units and period. A positive aggregate cannot establish that specific household requests are met.
5. Appendix B: sent the ending reviewer the citation additions and source boundaries listed above, especially IRS, NHTSA, NIST, California notice review, OSHA, land-trust leases, Freeman's certificate, chimney components, insulation, Toyota, and the dated food-recovery target.

## Verification and limits

Read each replacement back from disk, then read the complete unified diffs against preserved v0.10.1. A source reconstruction check replayed every recorded replacement against v0.10.1 and matched all eleven live sections exactly. A negative control added an unrecorded line in memory; the check rejected it before passing the real files. This detects unrecorded edits, not factual truth.

Structural checks passed for one H1 per section, one Foundations heading per chapter, unchanged injected epigraph lines, existing local image targets, and no em dashes. Both dividers are byte-for-byte unchanged. These checks do not evaluate visual layout, image accuracy, link availability, or PDF/EPUB rendering. Parent owns shared diagram changes and final publication verification. No commit, deletion, deployment, or full build was performed.
