<script>
  // Generated by postforge. Do not edit; regenerate instead.
  //
  // The post lives in the app so it inherits the real navbar, footer and
  // layout. Markup is imported raw and injected; behaviour runs on mount.
  import { onMount } from 'svelte';
  import content from './content.html?raw';
  import init from './content.js';

  onMount(() => {
    init();
  });
</script>

<svelte:head>
  <title>The Easier Question</title>
  <meta name="description" content="Four checks came back green while the thing they were supposed to prove stayed false. Every one answered a question that was easier than the one being asked." />
  <meta name="robots" content="noindex, follow" />
</svelte:head>

<a class="pf-back-inline" href="/devlog">back to devlog</a>
<div class="postforge-post">
  {@html content}
</div>

<style>
  /* The generated stylesheet is emitted verbatim and scoped to the wrapper.
     :global is required because the markup arrives through {@html}, which
     Svelte does not compile and therefore cannot add scoping hashes to. */
  .pf-back-inline {
    /* width:fit-content matters: the host layout is a flex/grid container and
       stretches its children, so inline-block alone left this pill spanning the
       full page width. */
    display: inline-block;
    width: fit-content;
    align-self: start;
    margin: 1.4rem 0 0 1.4rem;
    font-family: ui-monospace, 'JetBrains Mono', Menlo, monospace;
    font-size: 0.74rem;
    text-decoration: none;
    color: #94a3b8;
    border: 1px solid #1e293b;
    border-radius: 999px;
    padding: 0.35rem 0.8rem;
  }
  .pf-back-inline:hover { color: #f1f5f9; border-color: #64748b; }

  .postforge-post :global(*) { box-sizing: border-box; }

    :global(:root) {
    --pf-bg:#0b0e14; --pf-surface:#141922; --pf-surface2:#1b2230; --pf-line:#232b39;
    --pf-ink:#e6edf7; --pf-muted:#93a1b8; --pf-accent:#f59e0b; --pf-accent2:#38bdf8;
    --pf-good:#34d399; --pf-bad:#f87171; --pf-warn:#fbbf24;
    --pf-max:46rem; --pf-bleed:66rem;
    --pf-mono: ui-monospace, "JetBrains Mono", SFMono-Regular, Menlo, monospace;
    --pf-sans: ui-sans-serif, system-ui, "Inter", -apple-system, sans-serif;
  }
  /* light-scheme tokens omitted: the host app is dark only */
  .postforge-post :global(*), .postforge-post :global(*::before), .postforge-post :global(*::after) {box-sizing:border-box}
    .postforge-post :global(.pf-body-shim) {margin:0;background:var(--pf-bg);color:var(--pf-ink);font-family:var(--pf-sans);
    font-size:1.06rem;line-height:1.7;-webkit-font-smoothing:antialiased}
  .postforge-post :global(.wrap) {max-width:var(--pf-max);margin:0 auto;padding:0 1.25rem}
  .postforge-post :global(.pf-bleed) {max-width:var(--pf-bleed);margin-inline:auto;padding:0 1.25rem}
  .postforge-post :global(.scroll-x) {overflow-x:auto;-webkit-overflow-scrolling:touch}
  .postforge-post :global(img), .postforge-post :global(svg), .postforge-post :global(canvas) {max-width:100%;display:block}img{height:auto}
  .postforge-post :global(a) {color:var(--pf-accent2)}
  .postforge-post :global(h1) {font-size:clamp(2.1rem,7vw,3.6rem);line-height:1.03;letter-spacing:-.035em;margin:0 0 .8rem}
  .postforge-post :global(h2) {font-size:clamp(1.4rem,3.4vw,1.95rem);line-height:1.18;margin:4rem 0 .9rem;letter-spacing:-.018em;scroll-margin-top:2rem}
  .postforge-post :global(h3) {font-size:1.06rem;margin:2.2rem 0 .4rem;color:var(--pf-accent);font-family:var(--pf-mono);font-weight:600}
  .postforge-post :global(p) {margin:0 0 1.15rem}
  .postforge-post :global(strong) {font-weight:650;color:var(--pf-ink)}
  .postforge-post :global(code.inline) {font-family:var(--pf-mono);font-size:.86em;background:var(--pf-surface2);padding:.12em .38em;border-radius:4px}

  /* Back link to the index. A generated post is a standalone file, so without
     this it is a dead end for anyone who lands on it directly. */
  .postforge-post :global(.pf-back) {position:fixed;top:.9rem;left:.9rem;z-index:70;font-family:var(--pf-mono);font-size:.72rem;
    text-decoration:none;color:var(--pf-muted);background:color-mix(in srgb,var(--pf-bg) 88%,transparent);
    border:1px solid var(--pf-line);border-radius:999px;padding:.35rem .75rem;backdrop-filter:blur(6px)}
  .postforge-post :global(.pf-back:hover) {color:var(--pf-ink);border-color:var(--pf-muted)}
  @media(max-width:900px){.pf-back{position:static;display:inline-block;margin:1rem 0 0 1.25rem}}

  /* progress + toc */
  .postforge-post :global(.pf-progress) {position:fixed;top:0;left:0;right:0;height:3px;background:transparent;z-index:60}
  .postforge-post :global(.pf-progress span) {display:block;height:100%;background:var(--pf-accent);transform:scaleX(0);transform-origin:0 50%}
  .postforge-post :global(.pf-toc) {position:sticky;top:1.5rem;font-family:var(--pf-mono);font-size:.76rem}
  .postforge-post :global(.pf-toc-h) {text-transform:uppercase;letter-spacing:.14em;color:var(--pf-muted);margin:0 0 .5rem}
  .postforge-post :global(.pf-toc ol) {list-style:none;margin:0;padding:0;border-left:1px solid var(--pf-line)}
  .postforge-post :global(.pf-toc li) {margin:0}
  .postforge-post :global(.pf-toc a) {display:block;padding:.3rem .7rem;color:var(--pf-muted);text-decoration:none;border-left:2px solid transparent;margin-left:-1px}
  .postforge-post :global(.pf-toc a:hover) {color:var(--pf-ink)}
  .postforge-post :global(.pf-toc a.on) {color:var(--pf-accent);border-left-color:var(--pf-accent)}
  @media(max-width:1180px){.pf-toc{display:none}}
  .postforge-post :global(.pf-layout) {display:grid;grid-template-columns:1fr;gap:0}
  /* Grid and flex items default to min-width:auto, which means they refuse to
     shrink below their CONTENT's min-content width. A .scroll-x child holding a
     660px min-width SVG therefore widened this whole column to 736px at a 390px
     viewport, and the overflow-x:auto never got a chance to scroll. min-width:0
     is what lets the scroll container actually do its job.
     No backticks in this file: the whole stylesheet is one template literal. */
  .postforge-post :global(.pf-layout>*) {min-width:0}
  @media(min-width:1181px){
  .postforge-post :global(.pf-layout) {grid-template-columns:minmax(0,1fr) 15rem;max-width:74rem;margin-inline:auto;gap:2.5rem;padding:0 1.25rem}
  .postforge-post :global(.pf-layout .wrap) {padding:0;max-width:var(--pf-max)}
  }

  /* hero */
  .postforge-post :global(.pf-hero) {position:relative;margin-bottom:2.5rem}
  .postforge-post :global(.pf-hero-img) {width:100%;height:clamp(200px,34vw,380px);object-fit:cover;border-radius:14px;filter:saturate(.72) contrast(1.06)}
  /* Only the bottom edge is shaded, enough to seat the image against the page.
     Fading the whole frame washed the photograph out to near white in light mode. */
  .postforge-post :global(.pf-hero-shade) {position:absolute;inset:0;border-radius:14px;
    background:linear-gradient(180deg,transparent 0%,transparent 62%,color-mix(in srgb,var(--pf-bg) 62%,transparent) 100%)}
  .postforge-post :global(.pf-hero-credit) {font-family:var(--pf-mono);font-size:.68rem;color:var(--pf-muted);margin-top:.5rem}
  .postforge-post :global(.pf-hero-credit a) {color:var(--pf-muted)}
  .postforge-post :global(.byline) {font-family:var(--pf-mono);font-size:.72rem;color:var(--pf-muted);text-transform:uppercase;letter-spacing:.17em;margin:0 0 1.2rem}
  .postforge-post :global(.dek) {color:var(--pf-muted);font-size:clamp(1.05rem,2.4vw,1.3rem);line-height:1.5;margin:0 0 2rem}

  /* stat strip */
  .postforge-post :global(.pf-stats) {display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:1px;
    background:var(--pf-line);border:1px solid var(--pf-line);border-radius:12px;overflow:hidden;margin:2rem 0}
  .postforge-post :global(.pf-stat) {background:var(--pf-surface);padding:1rem .9rem;text-decoration:none;display:block;transition:background .2s}
  .postforge-post :global(.pf-stat:hover) {background:var(--pf-surface2)}
  .postforge-post :global(.pf-stat-n) {display:block;font-family:var(--pf-mono);font-size:1.7rem;font-weight:700;color:var(--pf-ink);letter-spacing:-.02em}
  .postforge-post :global(.pf-stat[data-tone=bad] .pf-stat-n) {color:var(--pf-bad)}
  .postforge-post :global(.pf-stat[data-tone=good] .pf-stat-n) {color:var(--pf-good)}
  .postforge-post :global(.pf-stat[data-tone=accent] .pf-stat-n) {color:var(--pf-accent)}
  .postforge-post :global(.pf-stat-l) {display:block;font-size:.78rem;color:var(--pf-muted);margin-top:.15rem;line-height:1.35}
  .postforge-post :global(.pf-stat-s) {display:block;font-family:var(--pf-mono);font-size:.66rem;color:var(--pf-muted);opacity:.75;margin-top:.3rem}

  /* tldr */
  .postforge-post :global(.pf-tldr) {background:var(--pf-surface);border:1px solid var(--pf-line);border-left:3px solid var(--pf-accent);
    border-radius:0 12px 12px 0;padding:1.2rem 1.4rem;margin:2.5rem 0}
  .postforge-post :global(.pf-tldr-h) {font-family:var(--pf-mono);font-size:.72rem;text-transform:uppercase;letter-spacing:.15em;
    color:var(--pf-accent);margin:0 0 .7rem}
  .postforge-post :global(.pf-tldr-list) {margin:0;padding-left:1.15rem;font-size:.99rem}
  .postforge-post :global(.pf-tldr-list li) {margin-bottom:.45rem}
  .postforge-post :global(.pf-tldr-verdict) {margin:.9rem 0 0;padding-top:.9rem;border-top:1px solid var(--pf-line);font-weight:600}

  /* finding cards */
  .postforge-post :global(.pf-cards) {display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:1rem;margin:2rem 0}
  .postforge-post :global(.pf-card) {background:var(--pf-surface);border:1px solid var(--pf-line);border-radius:12px;padding:1.1rem;
    display:flex;flex-direction:column}
  .postforge-post :global(.pf-card[data-tone=bad]) {border-top:3px solid var(--pf-bad)}
  .postforge-post :global(.pf-card[data-tone=accent]) {border-top:3px solid var(--pf-accent)}
  .postforge-post :global(.pf-card-h) {display:flex;gap:.8rem;align-items:flex-start;margin-bottom:.6rem}
  .postforge-post :global(.pf-card-icon) {image-rendering:pixelated;flex:0 0 auto}
  .postforge-post :global(.pf-card-n) {font-family:var(--pf-mono);font-size:.68rem;color:var(--pf-muted);letter-spacing:.1em}
  /* Card headlines are prose, not code. They inherit h3 otherwise, whose mono
     accent styling made them read as labels rather than titles. */
  .postforge-post :global(.pf-card-t) {font-size:1.06rem;margin:.1rem 0 0;line-height:1.25;letter-spacing:-.015em;
    font-family:var(--pf-sans);color:var(--pf-ink);font-weight:650}
  .postforge-post :global(.pf-card-lede) {font-size:.9rem;color:var(--pf-muted);margin:0 0 .8rem;line-height:1.55}
  .postforge-post :global(.pf-card-gap) {margin:0 0 .9rem;font-size:.8rem;display:grid;gap:.35rem}
  .postforge-post :global(.pf-card-gap div) {display:grid;grid-template-columns:5.2rem 1fr;gap:.5rem}
  .postforge-post :global(.pf-card-gap dt) {font-family:var(--pf-mono);font-size:.66rem;text-transform:uppercase;letter-spacing:.08em;color:var(--pf-muted)}
  .postforge-post :global(.pf-card-gap dd) {margin:0;color:var(--pf-muted)}
  .postforge-post :global(.pf-card-gap dd.pf-need) {color:var(--pf-ink);font-weight:600}
  .postforge-post :global(.pf-card-link) {margin-top:auto;font-family:var(--pf-mono);font-size:.75rem;text-decoration:none}

  /* evidence */
  .postforge-post :global(.pf-evidence) {border:1px solid var(--pf-line);border-radius:10px;background:var(--pf-surface);margin:1.5rem 0;overflow:hidden}
  .postforge-post :global(.pf-evidence[data-tone=good]) {border-left:3px solid var(--pf-good)}
  .postforge-post :global(.pf-evidence[data-tone=bad]) {border-left:3px solid var(--pf-bad)}
  .postforge-post :global(.pf-evidence[data-tone=accent]) {border-left:3px solid var(--pf-accent)}
  .postforge-post :global(.pf-evidence summary) {cursor:pointer;padding:.75rem 1rem;font-family:var(--pf-mono);font-size:.8rem;
    color:var(--pf-ink);list-style:none;display:flex;align-items:center;gap:.55rem;user-select:none}
  .postforge-post :global(.pf-evidence summary::-webkit-details-marker) {display:none}
  .postforge-post :global(.pf-evidence summary:hover) {background:var(--pf-surface2)}
  .postforge-post :global(.pf-ev-chev) {width:0;height:0;border-left:5px solid var(--pf-accent);border-top:4px solid transparent;
    border-bottom:4px solid transparent;transition:transform .18s;flex:0 0 auto}
  .postforge-post :global(.pf-evidence[open] .pf-ev-chev) {transform:rotate(90deg)}
  .postforge-post :global(.pf-ev-body) {padding:0 1rem 1rem;border-top:1px solid var(--pf-line)}
  .postforge-post :global(.pf-ev-body>*:first-child) {margin-top:1rem}

  /* code */
  .postforge-post :global(pre.code) {background:var(--pf-surface);border:1px solid var(--pf-line);border-left:3px solid var(--pf-accent2);
    border-radius:8px;padding:.9rem 1rem;overflow-x:auto;font-family:var(--pf-mono);font-size:.8rem;
    line-height:1.65;margin:1.5rem 0}
  .postforge-post :global(pre.code .c) {color:var(--pf-muted)} pre.code .k{color:var(--pf-accent2)} pre.code .s{color:var(--pf-good)}
  .postforge-post :global(pre.code .hl) {color:var(--pf-accent);font-weight:600}
  .postforge-post :global(pre.code .add) {color:var(--pf-good);display:block} pre.code .del{color:var(--pf-bad);display:block;opacity:.9}

  /* tables */
  .postforge-post :global(table) {border-collapse:collapse;width:100%;font-size:.9rem;min-width:32rem}
  .postforge-post :global(th), .postforge-post :global(td) {text-align:left;padding:.55rem .7rem;border-bottom:1px solid var(--pf-line);vertical-align:top}
  .postforge-post :global(th) {font-family:var(--pf-mono);font-size:.68rem;text-transform:uppercase;letter-spacing:.1em;color:var(--pf-muted);font-weight:600}
  .postforge-post :global(.pf-filter-wrap) {margin:1.6rem 0}
  .postforge-post :global(.pf-filter-label) {position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0)}
  .postforge-post :global(.pf-filter) {width:100%;max-width:22rem;background:var(--pf-surface);border:1px solid var(--pf-line);
    border-radius:8px;padding:.5rem .7rem;color:var(--pf-ink);font-family:var(--pf-mono);font-size:.82rem}
  .postforge-post :global(.pf-filter-count) {font-family:var(--pf-mono);font-size:.72rem;color:var(--pf-muted);margin-left:.7rem}

  /* scenes */
  .postforge-post :global(.pf-scene-wrap) {position:relative;margin:2.6rem auto}
  .postforge-post :global(.pf-canvas) {width:100%;aspect-ratio:16/9;background:transparent;display:block}
  .postforge-post :global(.pf-canvas-short) {aspect-ratio:21/9}
  .postforge-post :global(.pf-controls) {display:flex;flex-wrap:wrap;gap:.4rem;align-items:center;margin-bottom:.7rem}
  .postforge-post :global(.pf-controls-label) {font-family:var(--pf-mono);font-size:.66rem;text-transform:uppercase;
    letter-spacing:.12em;color:var(--pf-muted);margin-right:.15rem}
  .postforge-post :global(.pf-controls-sep) {width:1px;height:16px;background:var(--pf-line);margin:0 .45rem}
  .postforge-post :global(.pf-chip) {font-family:var(--pf-mono);font-size:.72rem;padding:.28rem .6rem;border-radius:999px;
    border:1px solid var(--pf-line);background:var(--pf-surface);color:var(--pf-muted);cursor:pointer;transition:all .16s}
  .postforge-post :global(.pf-chip:hover) {color:var(--pf-ink);border-color:var(--pf-muted)}
  .postforge-post :global(.pf-chip.on) {background:var(--pf-accent);border-color:var(--pf-accent);color:#0b0e14;font-weight:600}
  /* The readout is anchored to the CANVAS, not the figure. Anchoring it to the
     figure put it on top of the filter chips as soon as they wrapped to a second
     row on a narrower screen. */
  .postforge-post :global(.pf-stage) {position:relative}
  .postforge-post :global(.pf-readout) {position:absolute;top:.7rem;left:.7rem;font-family:var(--pf-mono);font-size:.72rem;
    background:color-mix(in srgb,var(--pf-bg) 86%,transparent);border:1px solid var(--pf-line);
    border-radius:6px;padding:.4rem .6rem;color:var(--pf-muted);pointer-events:none;max-width:calc(100% - 1.4rem)}
  .postforge-post :global(.pf-readout b) {color:var(--pf-ink)}
  .postforge-post :global(.pf-legend) {display:flex;gap:1rem;flex-wrap:wrap;font-family:var(--pf-mono);font-size:.7rem;color:var(--pf-muted);margin-top:.6rem}
  .postforge-post :global(.pf-legend i) {display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:.35rem}

  /* compare slider */
  .postforge-post :global(.pf-compare) {margin:2.5rem 0}
  .postforge-post :global(.pf-compare-stage) {position:relative;border-radius:10px;overflow:hidden;border:1px solid var(--pf-line);line-height:0}
  .postforge-post :global(.pf-compare-after) {width:100%}
  .postforge-post :global(.pf-compare-before) {position:absolute;inset:0;width:50%;overflow:hidden;border-right:2px solid var(--pf-accent)}
  .postforge-post :global(.pf-compare-before img) {height:100%;width:auto;max-width:none}
  .postforge-post :global(.pf-compare-range) {position:absolute;inset:auto 0 0;width:100%;margin:0;padding:0;opacity:0;height:100%;cursor:ew-resize}
  .postforge-post :global(.pf-compare-tag) {position:absolute;top:.5rem;font-family:var(--pf-mono);font-size:.66rem;text-transform:uppercase;
    letter-spacing:.1em;padding:.2rem .45rem;border-radius:4px;background:color-mix(in srgb,var(--pf-bg) 80%,transparent);color:var(--pf-muted)}
  .postforge-post :global(.pf-compare-tag-l) {left:.5rem} .pf-compare-tag-r{right:.5rem}

  /* misc prose furniture */
  .postforge-post :global(.callout) {border-left:3px solid var(--pf-accent);background:var(--pf-surface);padding:.95rem 1.15rem;
    border-radius:0 8px 8px 0;margin:1.9rem 0;font-size:.97rem}
  .postforge-post :global(.callout.warn) {border-left-color:var(--pf-bad)}
  .postforge-post :global(.callout.good) {border-left-color:var(--pf-good)}
  .postforge-post :global(.pull) {font-size:clamp(1.25rem,3.2vw,1.62rem);line-height:1.32;font-weight:650;border-top:1px solid var(--pf-line);
    border-bottom:1px solid var(--pf-line);padding:1.5rem 0;margin:3rem 0;letter-spacing:-.018em}
  .postforge-post :global(figure) {margin:2.6rem 0}
  .postforge-post :global(figcaption) {font-size:.84rem;color:var(--pf-muted);margin-top:.8rem;line-height:1.5}
  .postforge-post :global(.pf-marker) {display:flex;align-items:center;gap:.75rem;margin:4rem 0 .6rem}
  .postforge-post :global(.pf-marker img) {image-rendering:pixelated;flex:0 0 auto}
  .postforge-post :global(.pf-marker h2) {margin:0}
  .postforge-post :global(.pf-fn) {position:relative}
  .postforge-post :global(.pf-fn-mark) {font-family:var(--pf-mono);font-size:.7em;vertical-align:super;background:none;border:none;
    color:var(--pf-accent);cursor:pointer;padding:0 .1em}
  .postforge-post :global(.pf-fn-body) {display:none;background:var(--pf-surface);border:1px solid var(--pf-line);border-radius:8px;
    padding:.7rem .85rem;font-size:.85rem;color:var(--pf-muted);margin:.6rem 0}
  .postforge-post :global(.pf-fn.open .pf-fn-body) {display:block}
  .postforge-post :global(.reveal) {opacity:0;transform:translateY(14px);transition:opacity .7s ease,transform .7s ease}
  .postforge-post :global(.reveal.in) {opacity:1;transform:none}

  /* provenance */
  .postforge-post :global(.provenance) {border-top:1px solid var(--pf-line);margin-top:4.5rem;padding-top:2rem}
  .postforge-post :global(.prov-lede) {color:var(--pf-muted);font-size:.92rem}
  .postforge-post :global(.prov-grid) {display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:.7rem;margin:1.2rem 0}
  .postforge-post :global(.prov-grid div) {background:var(--pf-surface);border:1px solid var(--pf-line);border-radius:8px;padding:.6rem .75rem}
  .postforge-post :global(.prov-grid dt) {font-family:var(--pf-mono);font-size:.64rem;text-transform:uppercase;letter-spacing:.1em;color:var(--pf-muted)}
  .postforge-post :global(.prov-grid dd) {margin:.25rem 0 0;font-size:.84rem;word-break:break-word}
  .postforge-post :global(.prov-warn) {color:var(--pf-bad);font-family:var(--pf-mono);font-size:.7rem}
  .postforge-post :global(.prov-table) {font-size:.8rem}
  .postforge-post :global(.prov-raw summary) {cursor:pointer;font-family:var(--pf-mono);font-size:.76rem;color:var(--pf-muted)}
  .postforge-post :global(footer.pf-foot) {border-top:1px solid var(--pf-line);margin-top:3rem;padding:2rem 0 4rem;font-size:.86rem;color:var(--pf-muted)}

  /* Reduced motion: same selectors, later in the file, so source order wins the
     cascade with no priority override. SMIL and WebGL are handled in script. */
  @media (prefers-reduced-motion: reduce){
  .postforge-post :global(.reveal) {opacity:1;transform:none;transition:none}
  .postforge-post :global(.pf-ev-chev) {transition:none}
  }
</style>
