#!/usr/bin/env python3
"""Mirror the site's three font families into static/fonts/.

    python3 scripts/fetch_fonts.py            # rewrite static/fonts/
    python3 scripts/fetch_fonts.py --check    # compare, write nothing, exit 1 on drift

The site used to load Inter, JetBrains Mono and Outfit from fonts.googleapis.com
on every page. This asks Google for the same stylesheet a current Chrome gets,
downloads every woff2 it names, and writes static/fonts/fonts.css with the SAME
@font-face rules in the SAME order. Only the URLs change.

Two things are deliberate:

  * The rules are not merged into weight ranges. Google declares one face per
    weight, each pointing at the same variable file. A merged `400 900` range
    would render in-between weights differently from today: a 600 in JetBrains
    Mono, which Google's rules map to 700, would come out as a true 600.
  * Every subset is kept, not just latin. The unicode-range on each rule means a
    browser only downloads a subset when a page uses a character from it, so the
    Greek and Cyrillic files cost nothing until they are needed.

File names carry Google's version (inter-v20-latin.woff2), so static/_headers
can serve them as immutable. A newer version gets a new name.

Licences: all three families are SIL Open Font License 1.1. The texts live in
static/fonts/OFL-*.txt and must ship with the files.
"""
import hashlib
import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "static" / "fonts"
CSS_URL = ("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900"
           "&family=JetBrains+Mono:wght@400;500;700"
           "&family=Outfit:wght@300;400;500;600;700;800;900&display=swap")
# Google serves different formats to different browsers. A current Chrome gets
# woff2 variable files split by unicode-range, which is what the site was using.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")
SLUG = {"inter": "inter", "jetbrainsmono": "jetbrains-mono", "outfit": "outfit"}
LICENCES = {"Inter": "inter", "JetBrains-Mono": "jetbrainsmono", "Outfit": "outfit"}
HEADER = """/* Self-hosted copies of the three font families this site uses.
 *
 * These are the same files, and the same @font-face rules in the same order,
 * that fonts.googleapis.com served for
 *   Inter 400-900, JetBrains Mono 400/500/700, Outfit 300-900, display=swap
 * Only the URLs differ. Hosting them here means a page load makes no request
 * to Google, and the fonts no longer depend on a second host being reachable.
 *
 * The rules are NOT merged into weight ranges, on purpose. Google declares one
 * face per weight; a range would render in-between weights differently.
 *
 * All three families are under the SIL Open Font License 1.1 (OFL-*.txt, beside
 * this file). Generated by scripts/fetch_fonts.py. Do not edit by hand.
 */
"""


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def build():
    """Returns {filename: bytes} for everything that belongs in static/fonts/."""
    css = get(CSS_URL).decode("utf-8")
    blocks = list(re.finditer(r"/\* ([a-z-]+) \*/\s*@font-face \{(.*?)\}", css, flags=re.S))
    if not blocks:
        raise SystemExit("Google returned no @font-face rules. Nothing written.")
    names, files = {}, {}
    for m in blocks:
        subset, body = m.group(1), m.group(2)
        u = re.search(r"url\((https://fonts\.gstatic\.com/s/([a-z]+)/(v\d+)/[^)]+)\)", body)
        full, fam, ver = u.group(1), u.group(2), u.group(3)
        name = f"{SLUG[fam]}-{ver}-{subset}.woff2"
        if full in names:
            continue
        data = get(full)
        if data[:4] != b"wOF2":
            raise SystemExit(f"{name}: not a woff2 file. Nothing written.")
        names[full], files[name] = name, data
    local = css
    for full, name in names.items():
        local = local.replace(full, f"/fonts/{name}")
    if "gstatic" in local or "googleapis" in local:
        raise SystemExit("A Google address survived the rewrite. Nothing written.")
    files["fonts.css"] = (HEADER + local).encode("utf-8")
    for label, folder in LICENCES.items():
        files[f"OFL-{label}.txt"] = get(
            f"https://raw.githubusercontent.com/google/fonts/main/ofl/{folder}/OFL.txt")
    return files, len(blocks)


def main():
    check = "--check" in sys.argv[1:]
    files, rules = build()
    drift = []
    for name, data in sorted(files.items()):
        path = OUT / name
        same = path.exists() and path.read_bytes() == data
        if not same:
            drift.append(name)
        print(f"  {'same   ' if same else 'DIFFERS' if path.exists() else 'new    '} {len(data):7d}  "
              f"sha256:{hashlib.sha256(data).hexdigest()[:16]}  {name}")
    extra = sorted(p.name for p in OUT.glob("*") if p.is_file() and p.name not in files) if OUT.exists() else []
    for name in extra:
        print(f"  not from Google's current stylesheet: {name}")
    print(f"{rules} @font-face rules, {sum(1 for n in files if n.endswith('.woff2'))} font files, "
          f"{sum(len(d) for n, d in files.items() if n.endswith('.woff2')) / 1024:.0f} KB of fonts")
    if check:
        print("check: " + ("matches static/fonts/" if not drift and not extra else "static/fonts/ is out of date"))
        return 1 if drift or extra else 0
    OUT.mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (OUT / name).write_bytes(data)
    print(f"wrote {len(files)} files to {OUT.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
